services:
  postgresql:
    image: postgres:latest
    restart: always
    volumes:
      - ecommerce-db-data:/var/lib/postgresql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: localpw

volumes:
  ecommerce-db-data:
