spring:
  application:
    name: ecommerce-batch
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?profileSQL=true
    username: postgres
    password: localpw
    hikari:
      maximum-pool-size: 200
  batch:
    jdbc:
      initialize-schema: always
    metrics:
      enabled: true

logging:
  level:
    root: INFO
#    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    org.springframework.jdbc.core.StatementCreatorUtils: DEBUG
#    org.springframework.batch: DEBUG

management:
  metrics:
    export:
      prometheus:
        enabled: true
        pushgateway:
          enabled: true
          base-url: http://localhost:9091
          job: spring-batch
          push-rate: 10s
          shutdown-operation: push
    tags:
      application: ${spring.application.name}

prometheus:
  job:
    name: spring-batch
  pushgateway:
    url: http://localhost:9091
