spring:
  application:
    name: ecommerce-batch
  datasource:
    url: jdbc:mysql://localhost:5433/postgres?profileSQL=true
    username: postgres
    password: localpw
    hikari:
      maximum-pool-size: 200
    batch:
      initialize-schema: always
  logging:
    level:
      root: INFO
      org.springframework.jdbc.core.JdbcTemplate: DEBUG
      org.springframework.jdbc.core.StatementCreatorUtils: DEBUG